In [3]:
import sys
import os

# Add project root to Python path (adjust if needed)
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)

In [12]:
import pandas as pd
from src.utils import fetch_data
from src.features import add_technical_indicators

ticker = "TSLA"
df = fetch_data(ticker, interval="60m", period="3mo")
df = add_technical_indicators(df, ticker)
df.head()

[*********************100%***********************]  1 of 1 completed

,Datetime,Close_TSLA,High_TSLA,Low_TSLA,Open_TSLA,Volume_TSLA,rsi,stoch_k,stoch_d,williams_r,...,bollinger_l,atr,obv,mfi,macd,macd_signal,macd_diff,ema_20,sma_20,adx
33,2025-03-06 19:30:00+00:00,261.165009,266.609985,260.019989,260.450012,12802598,34.819396,4.914269,4.122071,-95.085731,...,258.120227,7.511473,-73344275,37.890883,-5.669164,-4.733686,-0.935478,271.824038,270.659085,22.142207
34,2025-03-06 20:30:00+00:00,263.429993,264.339996,260.549988,261.170013,8703774,38.064306,17.469264,8.201625,-82.530736,...,257.801411,7.245654,-64640501,43.468473,-5.637665,-4.914482,-0.723183,271.024605,270.550085,22.419514
35,2025-03-07 14:30:00+00:00,260.949310,266.249908,259.090088,259.274994,26537801,35.953189,9.091587,10.491707,-90.908413,...,257.467400,7.239523,-91178302,44.657965,-5.746629,-5.080911,-0.665717,270.065054,270.459526,22.253881
36,2025-03-07 15:30:00+00:00,254.389999,261.600006,254.309998,260.899994,15854379,31.049520,0.317090,8.959314,-99.682910,...,254.852858,7.243129,-107032681,44.083096,-6.289760,-5.322681,-0.967079,268.572191,269.579571,22.741829
37,2025-03-07 16:30:00+00:00,256.040009,256.095001,250.729996,254.419998,15145976,33.506359,18.431137,9.279938,-81.568863,...,252.988843,7.108977,-91886705,37.287754,-6.511988,-5.560542,-0.951445,267.378650,268.824772,23.616123

In [14]:

df["Datetime"] = pd.to_datetime(df["Datetime"])
df["Date"] = df["Datetime"].dt.date
df["Time"] = df["Datetime"].dt.time
df.drop(columns=["Datetime"], inplace=True)
df.head()

,Close_TSLA,High_TSLA,Low_TSLA,Open_TSLA,Volume_TSLA,rsi,stoch_k,stoch_d,williams_r,bollinger_m,...,obv,mfi,macd,macd_signal,macd_diff,ema_20,sma_20,adx,Date,Time
33,261.165009,266.609985,260.019989,260.450012,12802598,34.819396,4.914269,4.122071,-95.085731,270.659085,...,-73344275,37.890883,-5.669164,-4.733686,-0.935478,271.824038,270.659085,22.142207,2025-03-06,19:30:00
34,263.429993,264.339996,260.549988,261.170013,8703774,38.064306,17.469264,8.201625,-82.530736,270.550085,...,-64640501,43.468473,-5.637665,-4.914482,-0.723183,271.024605,270.550085,22.419514,2025-03-06,20:30:00
35,260.949310,266.249908,259.090088,259.274994,26537801,35.953189,9.091587,10.491707,-90.908413,270.459526,...,-91178302,44.657965,-5.746629,-5.080911,-0.665717,270.065054,270.459526,22.253881,2025-03-07,14:30:00
36,254.389999,261.600006,254.309998,260.899994,15854379,31.049520,0.317090,8.959314,-99.682910,269.579571,...,-107032681,44.083096,-6.289760,-5.322681,-0.967079,268.572191,269.579571,22.741829,2025-03-07,15:30:00
37,256.040009,256.095001,250.729996,254.419998,15145976,33.506359,18.431137,9.279938,-81.568863,268.824772,...,-91886705,37.287754,-6.511988,-5.560542,-0.951445,267.378650,268.824772,23.616123,2025-03-07,16:30:00