In [22]:
import sys
import os

# Add project root to Python path (adjust if needed)
project_root = os.path.abspath(os.path.join(os.getcwd(), ".."))
sys.path.append(project_root)

In [23]:
import pandas as pd
from src.utils import fetch_data
from src.features import add_technical_indicators

ticker = "TSLA"
df = fetch_data(ticker, interval="15m", period="1mo")
df = add_technical_indicators(df, ticker)
df["Datetime"] = pd.to_datetime(df["Datetime"])
df["Date"] = df["Datetime"].dt.date
df["Time"] = df["Datetime"].dt.time
cols = ["Date", "Time"] + [col for col in df.columns if col not in ["Date", "Time"]]
df = df[cols]
cols = ["Datetime"] + [col for col in df.columns if col not in ["Datetime"]]
df = df[cols]
df

[*********************100%***********************]  1 of 1 completed

,Datetime,Date,Time,Close_TSLA,High_TSLA,Low_TSLA,Open_TSLA,Volume_TSLA,rsi,stoch_k,...,bollinger_l,atr,obv,mfi,macd,macd_signal,macd_diff,ema_20,sma_20,adx
33,2025-04-29 15:15:00+00:00,2025-04-29,15:15:00,281.910004,282.329987,280.309998,281.170013,2980779,48.426374,24.825766,...,276.600011,3.356136,2541890,45.645573,-0.175029,-0.119622,-0.055407,282.180169,281.636040,16.036223
34,2025-04-29 15:30:00+00:00,2025-04-29,15:30:00,283.579987,283.579987,280.899994,281.910004,2698605,53.034088,41.813582,...,277.445228,3.307840,5240495,45.823360,-0.053543,-0.106406,0.052863,282.313485,281.984039,15.052613
35,2025-04-29 15:45:00+00:00,2025-04-29,15:45:00,283.529999,284.660004,283.310913,283.561493,3175004,52.881788,41.305083,...,278.513508,3.167929,2065491,49.681988,0.038262,-0.077472,0.115734,282.429344,282.334834,14.249363
36,2025-04-29 16:00:00+00:00,2025-04-29,16:00:00,283.980011,284.799988,283.489990,283.549896,2346550,54.158089,45.882809,...,279.542411,3.035220,4412041,47.989327,0.145650,-0.032848,0.178498,282.577026,282.665836,13.559972
37,2025-04-29 16:15:00+00:00,2025-04-29,16:15:00,282.760010,284.009888,282.470001,284.004913,2432242,50.188977,33.472410,...,279.968848,2.928411,1979799,43.481719,0.130805,-0.000117,0.130922,282.594453,282.811586,12.715728
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,2025-05-27 18:45:00+00:00,2025-05-27,18:45:00,359.721405,361.640015,359.500000,360.880005,3006461,63.054269,54.591590,...,353.516402,2.080751,276787769,73.579316,3.944117,4.385681,-0.441564,357.824334,358.965945,45.498559
542,2025-05-27 19:00:00+00:00,2025-05-27,19:00:00,359.049988,359.720001,358.600006,359.720001,3366626,60.290333,36.375665,...,353.813478,2.012225,273421143,66.392464,3.568183,4.222181,-0.653998,357.941063,359.109944,43.465739
543,2025-05-27 19:15:00+00:00,2025-05-27,19:15:00,359.890015,360.369995,358.620087,359.059998,3708636,62.504826,45.682712,...,354.139963,1.993489,277129779,66.735189,3.299995,4.037744,-0.737749,358.126677,359.287950,41.888028
544,2025-05-27 19:30:00+00:00,2025-05-27,19:30:00,360.399994,360.540009,357.799988,359.899994,4133538,63.823825,43.405628,...,354.594347,2.046812,281263317,57.887584,3.092952,3.848785,-0.755834,358.343184,359.514450,39.847802
545,2025-05-27 19:45:00+00:00,2025-05-27,19:45:00,362.751007,363.000000,359.209991,360.382507,7389679,69.202466,82.654460,...,355.350568,2.171326,288652996,61.978224,3.083036,3.695636,-0.612599,358.762976,359.920250,39.046001